# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  target-branch: "dev-rework"
  open-pull-requests-limit: 5
  pull-request-branch-name:
    separator: "-"
  reviewers:
    - "GSculerlor"
  ignore:
    - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
      versions:
      - "> 2.2.6"
    - dependency-name: NUnit3TestAdapter
      versions:
      - ">= 3.16.a, < 3.17"
    - dependency-name: Microsoft.NET.Test.Sdk
      versions:
      - 16.9.1
    - dependency-name: NUnit
      versions:
      - 3.13.1
