clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: 'osu.Game.Rulesets.Cytosu\osu.Game.Rulesets.Cytosu.csproj'
  version: '0.0.{build}'
cache:
  - '%LOCALAPPDATA%\NuGet\v3-cache -> appveyor.yml'
before_build:
  - ps: dotnet --info
  - ps: nuget restore -verbosity quiet
build:
  project: osu.Game.Rulesets.Cytosu.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true